<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>NES_Box_Art</RootNamespace>
    <UserSecretsId>e8781909-aab9-4c8a-b4e6-c36b82ccd226</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IGDB" Version="6.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
